global:
  dependencies:
    python:
      - forge-sdk==5.0.9
      - forge-cli==5.0.10
      - cecs==5.0.2
      - services/*.py
  env:
    PROJECT_SLUG: '{{cookiecutter.project_slug}}'
{% raw %}
    LOG_LEVEL: INFO

    # Misc
    DEFAULT_TIME_ZONE: Europe/Zagreb

  secrets:
    MONGO_CLIENT_PASSWORD: admin
    POSTGRES_CLIENT_PASSWORD: admin

  cecs:
    params: -e venv

  repository: nexus.vingd.net

services:

  rule-engine:
    type: java
    db:
      mongo: true
    resources:
      cpu: 200m
      memory: 1350Mi

  heartbeat:
    package: heartbeat
    type: python
    version: 5.0.4
    env:
      HEARTBEAT_CYCLE: 30
    db:
      mongo: true
    dependencies:
      - rule-engine-api==5.0.9
    resources:
      cpu: 69m
      memory: 65Mi

  control-panel:
    type: django
    version: 0.0.3
    https: true
    db:
      postgres: true
    image:
      static: true
    env:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: '{{ env.CONTROL_PANEL_ADMIN_PASSWORD | default("admin") }}'
      SITE_URL: '{{ "control-panel." + env.get("HOST_DOMAIN", "") }}'
      INTERNAL_SITE_URL: http://control-panel
      SECRET_KEY: KiOx1YWV1AaDdXmj6PdiFdsXi9iiGUghYskxeUxAQSAEODkB4E
      REPO: 'https://commit-bot:{{ env.COMMIT_TOKEN }}@{{ env.get("CI_REPOSITORY_URL", "").split("@")[1] }}'
      BRANCH: '{{ env.CI_COMMIT_BRANCH }}'
      DATA_HASH: '{{ file_hash("services/control_panel/configuration.yaml") }}'
    resources:
      cpu: 25m
      memory: 150Mi
{% endraw %}
