{% raw %}
global:
  env:
    PULSAR_URL: {{ env.PULSAR_URL }}
    PULSAR_ENDPOINT_URL: {{ env.PULSAR_ENDPOINT_URL }}

    MONGO_CLIENT_HOST: {{ env.MONGO_CLIENT_HOST }}
    MONGO_CLIENT_USERNAME: {{ env.MONGO_CLIENT_USERNAME }}

    POSTGRES_CLIENT_HOST: {{ env.POSTGRES_CLIENT_HOST }}
    POSTGRES_CLIENT_PORT: {{ env.POSTGRES_CLIENT_PORT }}
    POSTGRES_CLIENT_USERNAME: {{ env.POSTGRES_CLIENT_USERNAME }}

    REDIS_URL: {{ env.REDIS_URL }}

  secrets:
    MONGO_CLIENT_PASSWORD: {{ env.MONGO_CLIENT_PASSWORD }}

    POSTGRES_CLIENT_PASSWORD: {{ env.POSTGRES_CLIENT_PASSWORD }}
{% endraw %}