{% raw -%}
global:
  env:
    INTERNAL_CONTROL_PANEL_URL: '{{ env.CONTROL_PANEL_URL | default("http://localhost:8100", true) }}'

services:

  control-panel:
    port: 8100
    env:
      SITE_URL: '{{ env.CONTROL_PANEL_URL | default("http://localhost:8100", true) }}'
{% endraw %}